spring:
  application:
    name: sdjpa-intro
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE