spring:
  datasource:
    username: bookuser
    password: password!!123
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  flyway:
    user: bookadmin
    password: password!!123
  sql:
    init:
      mode: always